### ISSUE TITLE
OCIO OpenGL code should be upgraded for OCIO 2 with new GPU API

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/openfx-io#1]
OCIO 2 with new GPU API: https://github.com/imageworks/OpenColorIO/pull/539

Sample use of the new GPU API: https://github.com/imageworks/OpenColorIO/blob/master/src/apps/ociodisplay/main.cpp

Changes to ociodisplay when it was switched to the new API: https://github.com/imageworks/OpenColorIO/pull/539/files#diff-6bb1a574c942a19eb51ffb7cee789b9c

There is still no official OCIO 2 release, so this can wait

**Comment by devernay** [comment]
The OCIO 2 code has to be inserted here: https://github.com/NatronGitHub/openfx-io/blob/master/IOSupport/GenericOCIOOpenGL.cpp#L190

please keep the OCIO 1 code for reference and compatibility

**Comment by ghost** [comment]
There's currently no implementation of OCIO2 around line 190, and my build failed due to the `#error`, what can I do?

- edit: I come from the AUR here: https://aur.archlinux.org/packages/openfx-io/

**Comment by devernay** [comment]
OCIO 2 was not released yet. just compile from openfx-io HEAD, not 2.3.14 or find a way to make this patch to the source code: https://github.com/NatronGitHub/openfx-io/commit/b976e9d6444f8f79dca5e6bb6f442cdbcb4e8f63

**Comment by ghost** [comment]
Thanks, I tried `git checkout` and it worked!

**Comment by davej453** [comment]
I'm getting an error from this when building via AUR. Is there an expected update for OCIO v2 soon? I'm not sure how to get this working otherwise. Could the code be updated to build without the check for OCIO v2 for the meantime? Thanks

**Comment by ghost** [comment]
It's an extremely stupid workaround, although it works.

You can clone the PKGBUILD file from AUR and build the package yourself.

- Remove the `#error` and `else` code [here](https://github.com/NatronGitHub/openfx-io/blob/master/IOSupport/GenericOCIOOpenGL.cpp#L190)

<del><code>#error "Code must be upgraded for OCIO 2 with new GPU API"</code></del>
<del><code>#else</code></del>

It will bypass the version check then and do `makepkg` manually.

**Comment by devernay** [comment]
@lhy0403 : https://github.com/NatronGitHub/openfx-io/commit/b976e9d6444f8f79dca5e6bb6f442cdbcb4e8f63 is a much better fix, and it's been pushed a few days ago

**Comment by davej453** [comment]
@devernay It seems the code you linked to is what's causing the error. It's checking for OCIO v2 at line 190 but there is none yet. @lhy0403 Is this an AUR PKGBUILD issue?

**Comment by devernay** [comment]
It's checking if the major version number of ocio is more than one. For the current version of ocio it's exactly one. The previous check was checking if version > 1.1.0, because I didn't know when the new gpu API would be released. And they released 1.1.1 without the new gpu API, which is why it broke. https://github.com/NatronGitHub/openfx-io/commit/b976e9d6444f8f79dca5e6bb6f442cdbcb4e8f63 fixes that

**Comment by davej453** [comment]
@devernay Thank you for the clarification. What you're saying makes sense and I have confirmed I am up to date with ocio 1.1.1 but I still get this error when attempting to build from the AUR:
`../IOSupport/GenericOCIOOpenGL.cpp:190:2: error: #error "Code must be upgraded for OCIO 2 with new GPU API"
 #error "Code must be upgraded for OCIO 2 with new GPU API"
`
@lhy0403 Would you be so kind as to share your PKGBUILD? I can't seem to get it to work they way you described.

**Comment by ghost** [comment]
@davej453  My PKGBUILD was not modified, as I am using yaourt and which basically clones the 'bare' repo from here. The instruction in PKGBUILD seems to be OK.

What I actually did was removing the condition check around L190 (to bypass that `#error` instruction), before `make` touches this file, (`make` always runs so fast....).


EDIT: I checked that AUR, it says the current version of `opencolorio` is actually `1.1.1-1`
 
![image](https://user-images.githubusercontent.com/18734999/57012813-e527bb00-6c3a-11e9-93c1-f697e06e1e91.png)

**Comment by davej453** [comment]
@lhy0403 I was able to get it to work by forking it and making the change in my own branch then editing the PKGBUILD to load from my repo. Not a very elegant or long term solution but it got Natron to build finally.

> EDIT: I checked that AUR, it says the current version of `opencolorio` is actually `1.1.1-1`

This is what confuses me... Is v1.1.1-1 supposed to be true against the check for 'version > 1'?

Also, I found via this reference https://vfxplatform.com/ that OCIO v2 isn't due until 2021?! I just don't understand why this commit would be added at this time if it doesn't pass the conditional on build.

**Comment by devernay** [comment]
major version for 1.1.1 is 1, which is not >1

**Comment by davej453** [comment]
Right, so since v2 doesn't exist and this returns an error if the version is not > 1, why is it in place currently?

**Comment by Caeglathatur** [comment]
Also confused. Is *anyone* currently able to build this with this check?

For fellow AUR users (basically @lhy0403's workaround, but with more detail):
1. Download snapshot from AUR: https://aur.archlinux.org/cgit/aur.git/snapshot/openfx-io.tar.gz
2. Extract and `cd` into the dir.
3. `makepkg -si --asdeps`. Wait for it to fail (source code is downloaded).
4. In `src/openfx-io/IOSupport/GenericOCIOOpenGL.cpp`, remove lines 190-191. https://github.com/NatronGitHub/openfx-io/blob/Natron-2.3.14/IOSupport/GenericOCIOOpenGL.cpp#L190-L191
5. `makepkg -si --asdeps --noextract`
6. Proceed to build/install Natron.

EDIT: Just saw that someone has posted a fix in the AUR comments. It carries out the same workaround. https://aur.archlinux.org/packages/openfx-io/#comment-695140

**Comment by devernay** [comment]
> Right, so since v2 doesn't exist and this returns an error if the version is not > 1, why is it in place currently?

To be clear:

- It WAS in place when Natron 2.3.14 was released.
- At that time, OCIO 1.1.1 was not released, and it was not clear which OCIO version would implement the new API. How can you be forward-compatible without knowing the future?
- The version currently in the master branch has a fix, and will break if OCIO >= 2.0 is detected

**Comment by ghost** [comment]
My Archlinux received an update from AUR today, and it's currently working.

**Comment by devernay** [comment]
fixed by #16
