### ISSUE TITLE
Build errors on archlinux-manjaro

### ISSUE THREAD

**Issue by Area51Kacz** [NatronGitHub/openfx-io#12]
openfx-io version: 2.4
libseexpr2 2.11 (aur)
openimageio 2.2.13.0

build log
https://pastebin.com/vdwG46sd

key errors

```

Package 'IlmBase', required by 'virtual:world', not found
Package IlmBase was not found in the pkg-config search path.
Perhaps you should add the directory containing `IlmBase.pc'
```
```

Package 'IlmBase', required by 'virtual:world', not found
../EXR/ReadEXR.cpp:42:10: fatal error: ImfPixelType.h: No such file or directory
   42 | #include <ImfPixelType.h>
```

**Comment by rodlie** [comment]
Install OpenEXR.

**Comment by bcbnz** [comment]
I found this issue when searching to help with a related report with Arch. IlmBase is no longer available in OpenEXR (see AcademySoftwareFoundation/openexr#929) and so anything which uses it will fail to build on distros using the latest OpenEXR version.

**Comment by Area51Kacz** [comment]
@bcbnz and... how we could fix it  (beyond  using natron-bin)  extra/openexr 3.0.1-2

**Comment by rodlie** [comment]
As a temp fix just remove references to ilmbase.

Makefile:
https://github.com/NatronGitHub/openfx-io/blob/master/Makefile.master#L21

CMake (requires a bit more work):
https://github.com/NatronGitHub/openfx-io/blob/master/cmake/Modules/FindOpenEXR.cmake

**Comment by Area51Kacz** [comment]
purgin all IlmBase  references?

thats all?

**Comment by devernay** [comment]
Note that we haven't tested openexr 3.0 yet

**Comment by Area51Kacz** [comment]
So  (till  openexr3 its tested)  ... its better to rely on appimages/snap/official binary?

**Comment by devernay** [comment]
No: download the binaries from our site.
These are the only ones we support.
These are built using a publicly available docker image, and you can even build these yourself with one command.

**Comment by devernay** [comment]
Are you trying to build these plugins for something else than Natron? All the image reading plugins are designed for Natron. Only the SeExpr plugins may be used with other OpenFX hosts, but you may have compatibility issues

**Comment by rhysday** [comment]
Is removing all references in ILMBASE the current fix?

**Comment by rhysday** [comment]
I've tried removing all reference to ilmbase but I get a fatal error of SeExpression.h not existing.

`In file included from ../IOSupport/GenericReader.h:30,
                 from ../IOSupport/GenericReader.cpp:25:
../IOSupport/GenericReader.cpp: In member function ‘virtual void OFX::IO::GenericReaderPlugin::changedFilename(const OFX::InstanceChangedArgs&)’:
../SupportExt/ofxsMacros.h:46:38: note: ‘#pragma message: WARNING: OpenColorIO was updated, check that the following code is still necessary’
   46 | #   define WARN(exp) ("WARNING: " exp)
      |                                      ^
../IOSupport/GenericReader.cpp:2086:17: note: in expansion of macro ‘WARN’
 2086 | #pragma message WARN("OpenColorIO was updated, check that the following code is still necessary")
      |                 ^~~~
  CXX      Linux-64-release/GenericWriter.o
In file included from ../SupportExt/ofxsMultiPlane.h:43,
                 from ../IOSupport/GenericWriter.h:30,
                 from ../IOSupport/GenericWriter.cpp:25:
../IOSupport/GenericWriter.cpp: In member function ‘void OFX::IO::GenericWriterPlugin::outputFileChanged(OFX::InstanceChangeReason, bool, bool)’:
../SupportExt/ofxsMacros.h:46:38: note: ‘#pragma message: WARNING: OpenColorIO was updated, check that the following code is still necessary’
   46 | #   define WARN(exp) ("WARNING: " exp)
      |                                      ^
../IOSupport/GenericWriter.cpp:2113:17: note: in expansion of macro ‘WARN’
 2113 | #pragma message WARN("OpenColorIO was updated, check that the following code is still necessary")
      |                 ^~~~
  CXX      Linux-64-release/SequenceParsing.o
  CXX      Linux-64-release/SeExpr.o
../SeExpr/SeExpr.cpp:58:10: fatal error: SeExpression.h: No such file or directory
   58 | #include <SeExpression.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [../openfx/Support/Plugins/Makefile.master:83: Linux-64-release/SeExpr.o] Error 1
make[1]: Leaving directory '/home/me/.local/src/openfx-io/IO'
make: *** [Makefile:23: IO] Error 2`

**Comment by devernay** [comment]
openexr 3 is now supported, but we still use seexpr 2.11 and ocio 1.1.
there is probably some work required to upgrade to seexpr 3, and work on ocio 2 is also in progress

**Comment by devernay** [comment]
the best solution is still too use the docker build, which is the one we use to provide portable linux binaries. It has all dependencies with correct versions.
