### ISSUE TITLE
Provide Pre-compiled Builds

### ISSUE THREAD

**Issue by Windows81** [NatronGitHub/openfx-io#37]
Hey.  I don't use Natron regularly, but am looking for a way to more efficiently write to files on Windows.  
- I read that the `WriteFFMPEG` node preforms better than the built-in `Write`, but understand that this information could be outdated.
- Additionally, I do not know if the source is already compiled into Natron.
- The link you posted on the README ([3rdparty_windows_32_and_64bits_msvc2010.zip](https://www.dropbox.com/s/s5yuh9k3kum99jp/3rdparty_windows_32_and_64bits_msvc2010.zip)) goes to a dead Dropbox archive.

Thanks in advance for the help!

**Comment by rodlie** [comment]
openfx-io is part of Natron.
